FROM payara/micro:5-SNAPSHOT

MAINTAINER black-root <ronald_reir21@hotmail.com>

ADD domain.xml /opt/payara/domain.xml
ADD MantenimientoTPI-ear-1.0-SNAPSHOT.ear /opt/payara/deployments/MantenimientoTPI-ear-1.0-SNAPSHOT.ear
ADD mysql-connector-java-5.1.45-bin.jar /opt/payara/mysql-connector-java-5.1.45-bin.jar

EXPOSE 4848 8009 8080 8181

